relativeURLs = true
title = "Yutao WANG (王裕韬)"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. candidate, Singapore Management University"
    logo = "IMG_0165.jpg" 
    
