baseURL = "https://Yutao-Wang-Econ.github.io/YutaoWangEcongithubio/"
relativeURLs = true
title = "Yutao WANG"
theme = "academimal2"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Assistant Professor, Fudan University"
    logo = "IMG_0165.jpg" 
    
